name: Deploy frontend to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  pages: write
  contents: read

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deploy-pages.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Crear .nojekyll
        run: touch frontend/.nojekyll

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload frontend folder
        uses: actions/upload-pages-artifact@v3
        with:
          path: frontend

      - name: Deploy to GitHub Pages
        id: deploy-pages
        uses: actions/deploy-pages@v4